# Generated by Django 6.0.7 on 2026-08-02 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='note',
            table='note',
        ),
    ]
